In [55]:
from scipy.stats import norm
import numpy as np
from sklearn.dummy import DummyRegressor
from sklearn.impute import SimpleImputer

1. 一定注意把你要运行的都运行了，不要留下某个块没运行就出结果了
2. hw1.2 supervise learning分两种，（1）classification: 一定要求题目说清楚了可能存在哪些子类，是香蕉还是苹果，如果之说categorize/group...没说子类就
   都不是。（2）regression：就是预测个数值出来。
3. hw1.4 Estimating the probability that an individual will develop lung cancer (or not) based on their height, weight, 
   and smoking history这个东西不是regression,是classification。也包括Estimating the success (or failure) probability
4. hw1.6 KNN是 non-parametric method
5. hw1.8 test Accuracy 是train和test的事
6. hw1.9 再做一遍 P(A|B)*P(B)=P(A,B)
7. hw1.12 注意题里给的是P(X=0.3,Y=0.6),求的是P(X=0.3|Y=0.6),用前者/P(Y=0.6)
8. hw1.14 给了D=norm(loc=...,scale=...)之后，下一步是D.cdf(...), 不要再用norm.cdf了
9. hw1.15 predict的时候记得代入得是数组[7.25], 其实就是一直出y的均值
10. hw1.18 比如给出k=5, x=9.53，那就是8，9，10，11，12（是从10，9.53先四舍五入了开始延伸的！）
11. hw2.2 比如给k=1,k=25，只能确定train RMSE的关系，=1的rmse更小，更flexible和variable（贴近原模型）
12. hw2.5 k越小越贴近原模型
13. hw2.6 impute是按均值  imputer=SimpleImputer(strategy='mean')
                            imputer.fit(X)
                            imputer.transform(X)
14. hw2.9 先看第一列有什么内容，按字母顺序排，再看第二列的东西按字母排，横着可能一共会有五个量，然后是哪个就选哪里是1，其余填0
15. hw2.11 MAE是mean不是max
16. hw2.12 注意底下给定的预测类别
17. hw3.3 variance, flexibility++; bias--; perform不知道的
18. hw3.5/3.6 注意还有train RMSE是可以确定的
19. hw3.13 记住SST和SSE的公式（sum square error）

In [21]:
# 0.7
D=norm(loc=8,scale=3.2)
D.cdf(9.22)-D.cdf(6.05)

0.3773531720729396

In [23]:
# 0.8
y_true = np.array([0.3, 4.1, 2. , 7.9, 6.2, 1.1, 2.3, 4.6, 3.5, 0.8])
y_pred = np.array([1. , 2.8, 1.2, 8.2, 6.9, 2.7, 1.8, 3.7, 4. , 3.6])
def RMSE(y_true, y_pred):
    return np.sqrt(np.mean((y_true-y_pred)**2))
RMSE(y_true, y_pred)

1.2292273996295395

In [39]:
# 1.14
D1=norm(loc=3.4+2.7*5.2,scale=0.5)
p1=1-D1.cdf(16.7)
D2=norm(loc=3.4+2.7*3.8,scale=0.5)
p2=1-D2.cdf(13.1)
D3=norm(loc=3.4+2.7*0.3,scale=0.5)
p3=1-D3.cdf(4.7)
print(p1,p2,p3)

0.9305633766666688 0.8686431189572694 0.1635430593276923


In [46]:
# 1.15
x = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
y = np.array([ 5.1,  4.4,  8.2,  8.6, 10.7, 12.4, 16.5, 17.5, 19.6, 20.5])
dummy=DummyRegressor()
dummy.fit(x,y)
dummy.predict([8.26])
np.mean(y)

12.35

In [51]:
# 1.17
7.2*1.88+1.38
x = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
y = np.array([ 4.8,  4.4,  8.1,  8. ,  9.7, 12.3, 13.1, 16.3, 19.9, 20.7])
np.mean(y[3:10])
np.mean(y)

11.73

In [60]:
# 2.6
X = np.array([[0.64, 8.31],
              [1.55, 6.69],
              [ np.nan, 6.58],
              [0.36, 5.69],
              [1.88,  np.nan],
              [0.35, 7.11],
              [2.83, 7.41],
              [2.3 , 8.6 ],
              [0.36, 8.46],
              [3.5 , 7.23]])
np.mean(X,axis=0)
imputer=SimpleImputer(strategy='mean')
imputer.fit(X)
imputer.transform(X)

array([[0.64      , 8.31      ],
       [1.55      , 6.69      ],
       [1.53      , 6.58      ],
       [0.36      , 5.69      ],
       [1.88      , 7.34222222],
       [0.35      , 7.11      ],
       [2.83      , 7.41      ],
       [2.3       , 8.6       ],
       [0.36      , 8.46      ],
       [3.5       , 7.23      ]])

In [62]:
# 2.7
X = np.array([['dog', 'green'],
              ['dog', 'green'],
              ['bird', 'blue'],
              ['dog', 'green'],
              ['bird', 'red'],
              ['bird', 'green'],
              ['bird', np.nan],
              ['bird', 'red'],
              ['cat', 'blue'],
              ['cat', 'green'],
              [np.nan, 'red'],
              ['bird', 'green']], dtype=object)
imputer2=SimpleImputer(strategy="most_frequent")
imputer2.fit(X)
imputer2.transform(X)

array([['dog', 'green'],
       ['dog', 'green'],
       ['bird', 'blue'],
       ['dog', 'green'],
       ['bird', 'red'],
       ['bird', 'green'],
       ['bird', 'green'],
       ['bird', 'red'],
       ['cat', 'blue'],
       ['cat', 'green'],
       ['bird', 'red'],
       ['bird', 'green']], dtype=object)

In [69]:
# 2.8
X = np.array([[ 9.6, 51.1],
              [ 5.1, 37.1],
              [ 3.5, 86.4],
              [ 1.6, 46.9],
              [ 3.1, 64.4],
              [ 0.1, 76.1],
              [ 1.5, 77.8],
              [ 8.2, 38.6],
              [ 1. ,  6.4],
              [ 8. , 87.4]])
meanx=np.mean(X,axis=0)
stdx=np.std(X,axis=0)
newx=(X-meanx)/stdx
np.std(newx,axis=0)

array([1., 1.])

In [73]:
# 2.11
y=np.array([5.34,4.72,5.99,4.81,5.6])
max0=[]
for i in range(5):
    mean0=abs((np.sum(y)-y[i])/4-y[i])
    max0.append(mean0)
np.mean(max0)

0.5270000000000007

In [75]:
# 3.13
X = np.array([[4.64, 5.53, 4.56, 5.56],
              [3.52, 5.76, 4.17, 4.64],
              [5.65, 6.72, 4.98, 3.7 ],
              [3.35, 7.26, 3.08, 4.64],
              [4.38, 3.85, 3.76, 3.79],
              [5.69, 4.09, 5.51, 5.33],
              [5.32, 5.03, 5.76, 4.28],
              [3.92, 5.17, 5.24, 5.59],
              [5.23, 5.76, 5.54, 5.52],
              [5.78, 4.79, 6.64, 4.47]])
y = np.array([0.9, -108.2, 104.1, -68.5, -149.8, 30.6, 23., -65.6, 73.5, 66.6])
SST=np.sum((y-np.mean(y))**2)
SST

64411.32400000001

In [83]:
# 3.13
y1_left=y[X[:,2]<=5]
SSE1_left=np.sum((y1_left-np.mean(y1_left))**2)
y1_right=y[X[:,2]>5]
SSE1_right=np.sum((y1_right-np.mean(y1_right))**2)
SSE1_left+SSE1_right

52189.308

In [94]:
# 3.14
def p(y):
    counts = np.array([np.sum(y == i) for i in np.unique(y)])
    return counts / len(y)
x = np.array([0.5, 1.6, 1.7, 1.7, 2.4, 3.3, 7.7, 7.8, 8.2, 9.2, 9.7, 10.])
y = np.array([2, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0])
yl=y[x<=4.6]
yr=y[x>4.6]
print(p(yl),p(yr),p(y))
groot=-np.sum(p(y)*np.log2(p(y)))
gl=-np.sum(p(yl)*np.log2(p(yl)))
gr=-np.sum(p(yr)*np.log2(p(yr)))
print(groot,gl,gr)
len(yl)/len(y)*gl+len(yr)/len(y)*gr

[0.5        0.33333333 0.16666667] [0.66666667 0.16666667 0.16666667] [0.58333333 0.25       0.16666667]
1.384431504340598 1.4591479170272448 1.2516291673878228


1.3553885422075338