In [1]:
0.63*0.92/(0.63*0.92+0.54*0.08)

0.9306358381502889

In [2]:
0.46*0.08/(0.46*0.08+0.37*0.92)

0.09756097560975609

In [8]:
0.13/0.37

0.35135135135135137

In [2]:
mu=5.2+2.8*0.3
import numpy as np
import scipy.stats as stats     # 很重要
n=stats.norm(loc=mu,scale=1.5)  # 很重要
1-n.cdf(8.2)

0.07493369953432705

In [6]:
from sklearn.dummy import DummyRegressor # 很重要，不是DummyClassifier
x = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
y = np.array([0, 1, 1, 0, 1, 0, 1, 0, 1, 1])

dummy_clf = DummyRegressor() # 很重要
dummy_clf.fit(x,y)
dummy_clf.predict([2.25])  # 也写成数组，不要写2.25，要写一维数组

array([0.6])

In [8]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split

In [20]:
x = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]).reshape(-1,1)
y = np.array([ 1.4,  6.5,  9.2,  9.7, 11.9, 14.1, 15. , 16.5, 19.7, 22.2])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)
#x_vtrain,x_validation,y_vtrain,y_validation=train_test_split(x_train,y_train,test_size=0.20,random_state=42)

(10, 1)

(8,)

In [35]:
knn001=KNeighborsRegressor(n_neighbors=1)
knn007=KNeighborsRegressor(n_neighbors=7)
knn010=KNeighborsRegressor(n_neighbors=10)
knn001.fit(x_train,y_train)
knn007.fit(x_train,y_train)     # 如果不问有关于validation的问题就不用knn001.fit(x_vtrain,y_vtrain),这是validation用的
knn010.fit(x_train,y_train)
knn001.predict(np.array(6.8).reshape(-1,1))*2.03+1.48



array([31.93])

In [34]:
knn007.predict(np.array(6.8).reshape(-1,1))*2.03+1.48

array([30.074])

In [32]:
2.03*6.8+1.48

15.283999999999999

In [36]:
knn010.predict(np.array(6.8).reshape(-1,1))*1.48+2.03

ValueError: Expected n_neighbors <= n_samples,  but n_samples = 8, n_neighbors = 10

In [43]:
3.3*2.11+0.53 #一定是b1x+b0 别搞反了

7.492999999999999

In [47]:
np.array([ 1.9,  5.6,  6.4,  8.7, 12.1, 13. , 15.7, 16.8, 19.4, 21.6]).mean()   
# 比如找k=5, 若x=3.3，要考虑找x=1,2,3 4,5

12.12

In [42]:
np.mean(np.array([ 3.2,  5.1,  7.7,  8.9, 11.1, 11.3, 16.1, 17.7, 18.4, 22.5]))


12.2