# Homework 02

In [30]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.neighbors import KNeighborsRegressor

In [3]:
X = np.array([[ 2.42,  9.91],
              [  np.nan, 12.51],
              [ 2.36, 12.42],
              [ 2.51, 12.76],
              [ 2.6 , 13.89],
              [ 2.74,  8.5 ],
              [ 2.9 ,   np.nan],
              [ 2.79,  9.88],
              [ 2.92, 11.67],
              [ 2.53,  8.77]])

In [5]:
impute_arr=SimpleImputer(strategy="mean")
impute_arr.fit(X)
impute_arr.transform(X)

array([[ 2.42      ,  9.91      ],
       [ 2.64111111, 12.51      ],
       [ 2.36      , 12.42      ],
       [ 2.51      , 12.76      ],
       [ 2.6       , 13.89      ],
       [ 2.74      ,  8.5       ],
       [ 2.9       , 11.14555556],
       [ 2.79      ,  9.88      ],
       [ 2.92      , 11.67      ],
       [ 2.53      ,  8.77      ]])

In [9]:
X = np.array([['bird', 'blue'],
              [np.nan, 'blue'],
              ['bird', 'green'],
              ['dog', 'blue'],
              ['dog', 'red'],
              ['bird', 'red'],
              ['dog', 'blue'],
              ['dog', np.nan],
              ['bird', 'green'],
              ['dog', 'red'],
              ['bird', 'green'],
              ['bird', 'blue']], dtype=object)

In [10]:
impute_arr=SimpleImputer(strategy="most_frequent")
impute_arr.fit(X)
impute_arr.transform(X)

array([['bird', 'blue'],
       ['bird', 'blue'],
       ['bird', 'green'],
       ['dog', 'blue'],
       ['dog', 'red'],
       ['bird', 'red'],
       ['dog', 'blue'],
       ['dog', 'blue'],
       ['bird', 'green'],
       ['dog', 'red'],
       ['bird', 'green'],
       ['bird', 'blue']], dtype=object)

In [19]:
X = np.array([[ 1.2, 10.6],
              [ 0.9, 55.8],
              [ 6.3, 34.3],
              [ 5.1, 77.1],
              [ 5.9, 20.9],
              [ 4.8, 77.6],
              [ 7.7, 80.7],
              [ 0.5, 65.4],
              [ 6.3,  9.2],
              [ 8.6, 17.8]])

In [20]:
mean_before=np.mean(X,axis=0) # axis=0是按照不同的维度操作，即X有两维，左右列分别求均值
mean_before

array([ 4.73, 44.94])

In [21]:
std_before=np.std(X,axis=0)
std_before

array([ 2.74337384, 27.92948979])

In [22]:
X_after=(X-mean_before)/std_before
X_after

array([[-1.28673677, -1.22952479],
       [-1.39609117,  0.38883632],
       [ 0.57228803, -0.38095934],
       [ 0.13487043,  1.15147109],
       [ 0.42648216, -0.86073896],
       [ 0.02551603,  1.16937331],
       [ 1.08260856,  1.28036711],
       [-1.54189704,  0.73255903],
       [ 0.57228803, -1.27965102],
       [ 1.41067176, -0.97173275]])

In [23]:
np.mean(X_after, axis=0)

array([1.55431223e-16, 4.44089210e-17])

In [24]:
np.std(X_after,axis=0)

array([1., 1.])

In [26]:
data = np.array([           # 注意下这个东西怎么写，两个[], 用np.array
    ['democrat', 'michigan'],
    ['democrat', 'wisconsin'],
    ['republican', 'wisconsin'],
    ['democrat', 'illinois'],
    ['republican', 'michigan'],
    ['republican', 'illinois']
])

In [29]:
one_hot=OneHotEncoder()
one_hot.fit(data)
one_hot.fit_transform(data).toarray()

array([[1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 0.]])

In [33]:
knn04=KNeighborsRegressor(4)
X=np.array([[0.49,0.07],[0.35,0.12],[0.08,0.82],[0.20,0.94],[0.26,0.50]])
y=np.array([3.26,3.25,4.68,4.95,3.71])
knn04.fit(X,y)

KNeighborsRegressor(n_neighbors=4)

In [44]:
y=np.array([5.21,4.69,3.92,5.00,6.75])
#y=np.array([2.83,4.60,2.73,3.63,2.79])
s=np.sum(y)
ans=[]
for i in range(5):
    ans.append(abs((s-y[i])/4-y[i]))
np.mean(ans)

0.8659999999999999