In [4]:
import numpy as np
from scipy.stats import norm

array([0.26945115, 0.25836321, 0.20455523])

In [5]:
# 8.02
x = np.array([0.61, 0.31, -1.23, -0.46, -0.34, -0.47, -0.43, 0.03, -0.24, 0.01])
eval_points = np.array([0.26,0.41,-0.61])

ans=np.empty(3)
kernel= lambda x:norm.pdf(x)
for i,point in enumerate(eval_points):
    ans[i]=1/len(x)*np.sum(kernel(point-x))
    
ans

array([0.32935497, 0.30799424, 0.33735332])

In [8]:
# 8.03
from scipy.spatial.distance import cdist

d = np.array([[0.62, 3.93], [3.49, 2.96], [0.99, 3.87], [2.72, 3.4], [1.52, 3.89], [2.22, 7.32], [2.24, 4.93], [2.52, 3.89], [3.75, 4.88], [5.53, 4.32], [6.14, 2.28], [5.3, 2.85]])
r = np.array([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0]])
c = np.array([[3.64, 3.24], [3.06, 4.02], [2.55, 4.87]])

distances = cdist(d, c)
distances

array([[3.09782182, 2.44165927, 2.14674172],
       [0.3176476 , 1.14389685, 2.12877899],
       [2.72385756, 2.07542767, 1.85299757],
       [0.9338094 , 0.70710678, 1.47979728],
       [2.2174084 , 1.54547727, 1.42172431],
       [4.3200463 , 3.40523127, 2.47212459],
       [2.19456146, 1.22494898, 0.31575307],
       [1.29495174, 0.55542776, 0.98045908],
       [1.64368488, 1.10258786, 1.20004167],
       [2.17680959, 2.48815192, 3.03033002],
       [2.67798432, 3.53751325, 4.42675954],
       [1.70519794, 2.52715255, 3.4121694 ]])

In [18]:
C_i=0
for xi,x in enumerate(d):
    for i in range(3):
        if r[xi][i]==1:
            C_i+=np.sum((x-c[i])**2)
            break
C_i

46.422599999999996

In [21]:
# 以下用来修改distance
new_r = np.zeros_like(distances)
new_r[np.arange(len(d)), np.argmin(distances, axis=1)] = 1
new_r

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [22]:
C_a=0
for xi,x in enumerate(d):
    for i in range(3):
        if new_r[xi][i]==1:
            C_a+=np.sum((x-c[i])**2)
            break
C_a

33.21739999999999

In [ ]:
# 8.04
d = np.array([[3.98, -0.27], [4.59, 1.59], [2.92, 1.8], [3.16, 1.39], [3.07, 4.84], [2.88, 4.19], [3.35, 5.34], [3.03, 4.73], [5.18, 5.49], [4.47, 2.08], [6.22, 3.96], [4.64, 3.83]])
r = np.array([[0.0, 1.0, 0.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0]])
c = np.array([[3.9, 3.16], [4.46, 2.5], [3.51, 4.08]])

C_i=0
for xi,x in enumerate(d):
    for i in range(3):
        if r[xi][i]==1:
            C_i+=np.sum((x-c[i])**2)
            break
C_i

29.105900000000002

In [25]:
sums=np.zeros((3,2))
counts=np.zeros(3)
for xi,x in enumerate(d):
    for i in range(3):
        if r[xi][i]==1:
            sums[i]+=x
            counts[i]+=1
            break
new_c = sums/counts.reshape(-1,1)
new_c

array([[3.78 , 2.815],
       [4.484, 1.75 ],
       [3.502, 4.918]])

In [26]:
C_a=0
for xi,x in enumerate(d):
    for i in range(3):
        if r[xi][i]==1:
            C_a+=np.sum((x-new_c[i])**2)
            break
C_a

22.512129999999996